name: Tests

on:
  push:
    branches: [ 1.x ]
  pull_request:
    branches: [ 1.x ]

  workflow_dispatch:

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        php:
          - "8.3"
        dependency-mode:
          - prefer-stable
          - prefer-lowest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Task
        uses: arduino/setup-task@v2

      - name: Install PHP with extensions
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          ini-values: zend.assertions=1
          tools: composer:v2

      - name: Install dependencies
        run: composer install --ansi

      - name: Update  dependencies
        run: composer update --${{ matrix.dependency-mode }} --ansi

      - name: Composer validation
        run: task composer-validate

      - name: Lint
        run: task lint

      - name: PHPStan
        run: task phpstan

      - name: PHPUnit
        run: task phpunity
